import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiCplusplus,
  SiOpenjdk,
  SiReact,
  SiNextdotjs,
  SiHtml5,
  SiTailwindcss,
  SiRedux,
  SiVuedotjs, // SiCss3 removed from here
  SiNodedotjs,
  SiExpress,
  SiSpring,
  SiFastapi,
  SiDjango,
  SiGraphql,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiGithubactions,
  SiJenkins,
  SiNginx,
  SiGit,
  SiGithub,
  SiFigma,
  SiPostman,
  SiLinux,
  SiJira,
  SiFirebase,
  SiVercel,
  SiMui,
  SiShadcnui,
  SiNestjs,
  SiCpanel,
  SiCucumber,
  SiCloudflare,
  SiExpo,
  SiSwagger
} from "react-icons/si";
import { FaJava, FaAws, FaCss3Alt, FaNodeJs } from "react-icons/fa"; // FaCss3Alt added here
import { TbBrandCSharp } from "react-icons/tb";
import { AiFillOpenAI } from "react-icons/ai";
import { DiGoogleCloudPlatform } from "react-icons/di";
import { GiCycle } from "react-icons/gi";
import { IoLogoFirebase } from "react-icons/io5";

export const iconMap = {
  java: FaJava,
  python: SiPython,
  javascript: SiJavascript,
  typescript: SiTypescript,
  cplusplus: SiCplusplus,
  c: SiOpenjdk,
  react: SiReact,
  nextdotjs: SiNextdotjs,
  html5: SiHtml5,
  css3: FaCss3Alt, // Updated to use the FontAwesome icon
  tailwindcss: SiTailwindcss,
  redux: SiRedux,
  vuedotjs: SiVuedotjs,
  nodedotjs: SiNodedotjs,
  express: SiExpress,
  spring: SiSpring,
  fastapi: SiFastapi,
  django: SiDjango,
  graphql: SiGraphql,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  sqlite: SiSqlite,
  amazonaws: FaAws,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  githubactions: SiGithubactions,
  jenkins: SiJenkins,
  nginx: SiNginx,
  git: SiGit,
  github: SiGithub,
  figma: SiFigma,
  postman: SiPostman,
  linux: SiLinux,
  jira: SiJira,
  firebase: IoLogoFirebase,
  vercel: SiVercel,
  //   nextdotjs: SiNextdotjs,
  mui: SiMui,
  shadcnui: SiShadcnui,
  nestjs: SiNestjs,
  openai: AiFillOpenAI,
  csharp: TbBrandCSharp,
  gcp: DiGoogleCloudPlatform,
  cpanel: SiCpanel,
  cucumber: SiCucumber,
  serenitybdd: GiCycle,
  cloudflare: SiCloudflare,
  expo: SiExpo,
  swagger: SiSwagger
};
